import { OpenWeatherWeather } from '../types';

export const OPENWEATHER_WEATHER_CONDITIONS: Record<
  number,
  OpenWeatherWeather
> = {
  200: {
    id: 200,
    main: 'Thunderstorm',
    description: 'Thunderstorm with light rain',
    icon: '11d',
  },
  201: {
    id: 201,
    main: 'Thunderstorm',
    description: 'Thunderstorm with rain',
    icon: '11d',
  },
  202: {
    id: 202,
    main: 'Thunderstorm',
    description: 'Thunderstorm with heavy rain',
    icon: '11d',
  },
  210: {
    id: 210,
    main: 'Thunderstorm',
    description: 'Light thunderstorm',
    icon: '11d',
  },
  211: {
    id: 211,
    main: 'Thunderstorm',
    description: 'Thunderstorm',
    icon: '11d',
  },
  212: {
    id: 212,
    main: 'Thunderstorm',
    description: 'Heavy thunderstorm',
    icon: '11d',
  },
  221: {
    id: 221,
    main: 'Thunderstorm',
    description: 'Ragged thunderstorm',
    icon: '11d',
  },
  230: {
    id: 230,
    main: 'Thunderstorm',
    description: 'Thunderstorm with light drizzle',
    icon: '11d',
  },
  231: {
    id: 231,
    main: 'Thunderstorm',
    description: 'Thunderstorm with drizzle',
    icon: '11d',
  },
  232: {
    id: 232,
    main: 'Thunderstorm',
    description: 'Thunderstorm with heavy drizzle',
    icon: '11d',
  },
  300: {
    id: 300,
    main: 'Drizzle',
    description: 'Light intensity drizzle',
    icon: '09d',
  },
  301: { id: 301, main: 'Drizzle', description: 'Drizzle', icon: '09d' },
  302: {
    id: 302,
    main: 'Drizzle',
    description: 'Heavy intensity drizzle',
    icon: '09d',
  },
  310: {
    id: 310,
    main: 'Drizzle',
    description: 'Light intensity drizzle rain',
    icon: '09d',
  },
  311: { id: 311, main: 'Drizzle', description: 'Drizzle rain', icon: '09d' },
  312: {
    id: 312,
    main: 'Drizzle',
    description: 'Heavy intensity drizzle rain',
    icon: '09d',
  },
  313: {
    id: 313,
    main: 'Drizzle',
    description: 'Shower rain and drizzle',
    icon: '09d',
  },
  314: {
    id: 314,
    main: 'Drizzle',
    description: 'Heavy shower rain and drizzle',
    icon: '09d',
  },
  321: { id: 321, main: 'Drizzle', description: 'Shower drizzle', icon: '09d' },
  500: { id: 500, main: 'Rain', description: 'Light rain', icon: '10d' },
  501: { id: 501, main: 'Rain', description: 'Moderate rain', icon: '10d' },
  502: {
    id: 502,
    main: 'Rain',
    description: 'Heavy intensity rain',
    icon: '10d',
  },
  503: { id: 503, main: 'Rain', description: 'Very heavy rain', icon: '10d' },
  504: { id: 504, main: 'Rain', description: 'Extreme rain', icon: '10d' },
  511: { id: 511, main: 'Rain', description: 'Freezing rain', icon: '13d' },
  520: {
    id: 520,
    main: 'Rain',
    description: 'Light intensity shower rain',
    icon: '09d',
  },
  521: { id: 521, main: 'Rain', description: 'Shower rain', icon: '09d' },
  522: {
    id: 522,
    main: 'Rain',
    description: 'Heavy intensity shower rain',
    icon: '09d',
  },
  531: {
    id: 531,
    main: 'Rain',
    description: 'Ragged shower rain',
    icon: '09d',
  },
  600: { id: 600, main: 'Snow', description: 'Light snow', icon: '13d' },
  601: { id: 601, main: 'Snow', description: 'Snow', icon: '13d' },
  602: { id: 602, main: 'Snow', description: 'Heavy snow', icon: '13d' },
  611: { id: 611, main: 'Snow', description: 'Sleet', icon: '13d' },
  612: {
    id: 612,
    main: 'Snow',
    description: 'Light shower sleet',
    icon: '13d',
  },
  613: { id: 613, main: 'Snow', description: 'Shower sleet', icon: '13d' },
  615: {
    id: 615,
    main: 'Snow',
    description: 'Light rain and snow',
    icon: '13d',
  },
  616: { id: 616, main: 'Snow', description: 'Rain and snow', icon: '13d' },
  620: { id: 620, main: 'Snow', description: 'Light shower snow', icon: '13d' },
  621: { id: 621, main: 'Snow', description: 'Shower snow', icon: '13d' },
  622: { id: 622, main: 'Snow', description: 'Heavy shower snow', icon: '13d' },
  701: { id: 701, main: 'Mist', description: 'Mist', icon: '50d' },
  711: { id: 711, main: 'Smoke', description: 'Smoke', icon: '50d' },
  721: { id: 721, main: 'Haze', description: 'Haze', icon: '50d' },
  731: { id: 731, main: 'Dust', description: 'Sand/dust whirls', icon: '50d' },
  741: { id: 741, main: 'Fog', description: 'Fog', icon: '50d' },
  751: { id: 751, main: 'Sand', description: 'Sand', icon: '50d' },
  761: { id: 761, main: 'Dust', description: 'Dust', icon: '50d' },
  762: { id: 762, main: 'Ash', description: 'Volcanic ash', icon: '50d' },
  771: { id: 771, main: 'Squall', description: 'Squalls', icon: '50d' },
  781: { id: 781, main: 'Tornado', description: 'Tornado', icon: '50d' },
  800: { id: 800, main: 'Clear', description: 'Clear sky', icon: '01d' },
  801: { id: 801, main: 'Clouds', description: 'Few clouds', icon: '02d' },
  802: {
    id: 802,
    main: 'Clouds',
    description: 'Scattered clouds',
    icon: '03d',
  },
  803: { id: 803, main: 'Clouds', description: 'Broken clouds', icon: '04d' },
  804: { id: 804, main: 'Clouds', description: 'Overcast clouds', icon: '04d' },
} satisfies Record<
  keyof typeof OPENWEATHER_WEATHER_CONDITIONS,
  OpenWeatherWeather
>;
